# Generated by Django 4.1.2 on 2022-11-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user-male.png', null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
