# Generated by Django 4.1.2 on 2022-11-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_session_status_student_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacos_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50, unique=True, verbose_name='Reg No')),
                ('fullname', models.CharField(max_length=100, verbose_name='Student Name')),
                ('level', models.ForeignKey(default='Select Level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.level')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.school_session')),
            ],
        ),
    ]
