# Generated by Django 4.1.2 on 2022-11-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_nacos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='nacos_id',
            name='semester',
        ),
        migrations.AddField(
            model_name='nacos_id',
            name='passport',
            field=models.ImageField(null=True, upload_to='passports/', verbose_name='Passport'),
        ),
        migrations.AddField(
            model_name='nacos_id',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.programme'),
        ),
    ]
