# Generated by Django 4.1.2 on 2022-11-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_programme_remove_nacos_id_semester_nacos_id_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacos_id',
            name='passport',
            field=models.ImageField(default='user-male.png', null=True, upload_to='passports/', verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='nacos_id',
            name='programme',
            field=models.ForeignKey(default='Select Programme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.programme'),
        ),
        migrations.AlterField(
            model_name='nacos_id',
            name='session',
            field=models.ForeignKey(default='Select Session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.school_session'),
        ),
    ]
