# Generated by Django 4.1.3 on 2022-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_nacos_id_passport_alter_nacos_id_programme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Payment Type')),
            ],
        ),
        migrations.AlterField(
            model_name='nacos_id',
            name='passport',
            field=models.ImageField(default='logo.png', null=True, upload_to='passports/', verbose_name='Passport'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_amount', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.level')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.payment_type')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.school_session')),
            ],
        ),
    ]
