# Generated by Django 4.1.3 on 2022-12-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_payment_type_alter_nacos_id_passport_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_mode',
        ),
    ]
