# Generated by Django 4.1.3 on 2022-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_transaction_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_type',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
